# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: system.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csystem.proto\x12\x06System\"Z\n\x04Task\x12#\n\ttask_type\x18\x01 \x01(\x0e\x32\x10.System.TaskType\x12\x17\n\x0ftask_identifier\x18\x02 \x01(\t\x12\x14\n\x0ctask_content\x18\x03 \x01(\t\"_\n\nTaskResult\x12#\n\ttask_type\x18\x01 \x01(\x0e\x32\x10.System.TaskType\x12\x17\n\x0ftask_identifier\x18\x02 \x01(\t\x12\x13\n\x0btask_result\x18\x03 \x01(\t\"+\n\x0eGetTaskRequest\x12\x19\n\x11\x63lient_identifier\x18\x01 \x01(\t\"U\n\x0fGetTaskResponse\x12&\n\x06status\x18\x01 \x01(\x0e\x32\x16.System.ResponseStatus\x12\x1a\n\x04task\x18\x02 \x01(\x0b\x32\x0c.System.Task\"c\n\x10PutResultRequest\x12&\n\x06status\x18\x01 \x01(\x0e\x32\x16.System.ResponseStatus\x12\'\n\x0btask_result\x18\x02 \x01(\x0b\x32\x12.System.TaskResult\";\n\x11PutResultResponse\x12&\n\x06status\x18\x01 \x01(\x0e\x32\x16.System.ResponseStatus*Q\n\x0eResponseStatus\x12\x0b\n\x07SUCCESS\x10\x00\x12\r\n\tTRY_LATER\x10\x01\x12\x0f\n\x0bTOOL_FAILED\x10\x02\x12\x12\n\x0eINTERNAL_ERROR\x10\x03*\x16\n\x08TaskType\x12\n\n\x06\x45NERGY\x10\x00\x32\x8e\x01\n\nSDDFactory\x12<\n\x07GetTask\x12\x16.System.GetTaskRequest\x1a\x17.System.GetTaskResponse\"\x00\x12\x42\n\tPutResult\x12\x18.System.PutResultRequest\x1a\x19.System.PutResultResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'system_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_RESPONSESTATUS']._serialized_start=507
  _globals['_RESPONSESTATUS']._serialized_end=588
  _globals['_TASKTYPE']._serialized_start=590
  _globals['_TASKTYPE']._serialized_end=612
  _globals['_TASK']._serialized_start=24
  _globals['_TASK']._serialized_end=114
  _globals['_TASKRESULT']._serialized_start=116
  _globals['_TASKRESULT']._serialized_end=211
  _globals['_GETTASKREQUEST']._serialized_start=213
  _globals['_GETTASKREQUEST']._serialized_end=256
  _globals['_GETTASKRESPONSE']._serialized_start=258
  _globals['_GETTASKRESPONSE']._serialized_end=343
  _globals['_PUTRESULTREQUEST']._serialized_start=345
  _globals['_PUTRESULTREQUEST']._serialized_end=444
  _globals['_PUTRESULTRESPONSE']._serialized_start=446
  _globals['_PUTRESULTRESPONSE']._serialized_end=505
  _globals['_SDDFACTORY']._serialized_start=615
  _globals['_SDDFACTORY']._serialized_end=757
# @@protoc_insertion_point(module_scope)
