# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import src.gRPC.system_pb2 as system__pb2


class SDDFactoryStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTask = channel.unary_unary(
                '/System.SDDFactory/GetTask',
                request_serializer=system__pb2.GetTaskRequest.SerializeToString,
                response_deserializer=system__pb2.GetTaskResponse.FromString,
                )
        self.PutResult = channel.unary_unary(
                '/System.SDDFactory/PutResult',
                request_serializer=system__pb2.PutResultRequest.SerializeToString,
                response_deserializer=system__pb2.PutResultResponse.FromString,
                )


class SDDFactoryServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PutResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SDDFactoryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTask': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTask,
                    request_deserializer=system__pb2.GetTaskRequest.FromString,
                    response_serializer=system__pb2.GetTaskResponse.SerializeToString,
            ),
            'PutResult': grpc.unary_unary_rpc_method_handler(
                    servicer.PutResult,
                    request_deserializer=system__pb2.PutResultRequest.FromString,
                    response_serializer=system__pb2.PutResultResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'System.SDDFactory', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SDDFactory(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/System.SDDFactory/GetTask',
            system__pb2.GetTaskRequest.SerializeToString,
            system__pb2.GetTaskResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PutResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/System.SDDFactory/PutResult',
            system__pb2.PutResultRequest.SerializeToString,
            system__pb2.PutResultResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
