# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: system.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csystem.proto\x12\x06System\"+\n\x0eGetTaskRequest\x12\x19\n\x11\x63lient_identifier\x18\x01 \x01(\t\"h\n\x0fGetTaskResponse\x12&\n\x06status\x18\x01 \x01(\x0e\x32\x16.System.ResponseStatus\x12\x17\n\x0ftask_identifier\x18\x02 \x01(\t\x12\x14\n\x0ctask_content\x18\x03 \x01(\t\"<\n\x10PutResultRequest\x12\x17\n\x0ftask_identifier\x18\x01 \x01(\t\x12\x0f\n\x07results\x18\x02 \x01(\t\";\n\x11PutResultResponse\x12&\n\x06status\x18\x01 \x01(\x0e\x32\x16.System.ResponseStatus*@\n\x0eResponseStatus\x12\x0b\n\x07SUCCESS\x10\x00\x12\r\n\tTRY_LATER\x10\x01\x12\x12\n\x0eINTERNAL_ERROR\x10\x02\x32\x95\x01\n\x11\x45nergyCalculation\x12<\n\x07GetTask\x12\x16.System.GetTaskRequest\x1a\x17.System.GetTaskResponse\"\x00\x12\x42\n\tPutResult\x12\x18.System.PutResultRequest\x1a\x19.System.PutResultResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'system_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_RESPONSESTATUS']._serialized_start=298
  _globals['_RESPONSESTATUS']._serialized_end=362
  _globals['_GETTASKREQUEST']._serialized_start=24
  _globals['_GETTASKREQUEST']._serialized_end=67
  _globals['_GETTASKRESPONSE']._serialized_start=69
  _globals['_GETTASKRESPONSE']._serialized_end=173
  _globals['_PUTRESULTREQUEST']._serialized_start=175
  _globals['_PUTRESULTREQUEST']._serialized_end=235
  _globals['_PUTRESULTRESPONSE']._serialized_start=237
  _globals['_PUTRESULTRESPONSE']._serialized_end=296
  _globals['_ENERGYCALCULATION']._serialized_start=365
  _globals['_ENERGYCALCULATION']._serialized_end=514
# @@protoc_insertion_point(module_scope)
